// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evolib.Databases.common3;

namespace evolib.Migrations.common3dbcontext
{
    [DbContext(typeof(Common3DBContext))]
    [Migration("20200702050402_DeleteReplayTable")]
    partial class DeleteReplayTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("evolib.Databases.common3.MatchMember", b =>
                {
                    b.Property<string>("matchId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("playersInfo");

                    b.HasKey("matchId");

                    b.ToTable("MatchMember");
                });

            modelBuilder.Entity("evolib.Databases.common3.ReplayViewNum", b =>
                {
                    b.Property<string>("matchId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<int>("ViewNum");

                    b.HasKey("matchId");

                    b.ToTable("ReplayViewNum");
                });
#pragma warning restore 612, 618
        }
    }
}
