// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evolib.Databases.common2;

namespace evolib.Migrations.common2dbcontext
{
    [DbContext(typeof(Common2DBContext))]
    [Migration("20200322003707_FirstStep")]
    partial class FirstStep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("evolib.Databases.common2.Friend", b =>
                {
                    b.Property<long>("playerIdL");

                    b.Property<long>("playerIdR");

                    b.Property<DateTime>("timeStamp");

                    b.HasKey("playerIdL", "playerIdR");

                    b.HasIndex("playerIdR");

                    b.ToTable("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
