// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evolib.Databases.common2;

namespace evolib.Migrations.common2dbcontext
{
    [DbContext(typeof(Common2DBContext))]
    [Migration("20201117221631_AddDisabledMobileSuit")]
    partial class AddDisabledMobileSuit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("evolib.Databases.common2.DisabledMobileSuit", b =>
                {
                    b.Property<string>("itemId");

                    b.Property<DateTime>("updateDate")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("itemId");

                    b.ToTable("DisabledMobileSuits");
                });

            modelBuilder.Entity("evolib.Databases.common2.Friend", b =>
                {
                    b.Property<long>("playerIdL");

                    b.Property<long>("playerIdR");

                    b.Property<DateTime>("timeStamp");

                    b.HasKey("playerIdL", "playerIdR");

                    b.HasIndex("playerIdR");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("evolib.Databases.common2.PlayerName", b =>
                {
                    b.Property<string>("playerName");

                    b.Property<long>("playerId");

                    b.Property<DateTime>("timeStamp")
                        .ValueGeneratedOnAdd();

                    b.HasKey("playerName");

                    b.ToTable("PlayerNames");
                });
#pragma warning restore 612, 618
        }
    }
}
