# version: 0.0
# os: operating-system-name
# files:
#   source-destination-files-mappings
# permissions:
#   permissions-specifications
# hooks:
#   deployment-lifecycle-event-mappings

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/packages
permissions:
  - object: /home/ec2-user/packages/scripts
    pattern: "*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 777
    type:
      - file
hooks:
#   BeforeInstall:
#     - location: scripts/install_dependencies.sh
#       timeout: 300
#       runas: root
  AfterInstall:
    - location: scripts/evomatching.AfterInstall.sh
      timeout: 300
      runas: root
#   ApplicationStart:
#     - location: scripts/start_server.sh
#     - location: scripts/create_test_db.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server.sh
#       timeout: 300
#       runas: root
