// <auto-generated />
using AuthenticationServer.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuthenticationServer.Migrations
{
    [DbContext(typeof(AuthDBContext))]
    [Migration("20200226060921_FirstStep")]
    partial class FirstStep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthenticationServer.Databases.Account", b =>
                {
                    b.Property<string>("account");

                    b.Property<string>("hashedPassword")
                        .IsRequired();

                    b.Property<int>("hostType");

                    b.Property<string>("nickname")
                        .IsRequired();

                    b.Property<int>("permission");

                    b.Property<string>("salt")
                        .IsRequired();

                    b.HasKey("account");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
