
- name: <MariaDB> repo認証用key登録
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0xF1656F24C74CD1D8
    state: absent

- name: <MariaDB> repo登録
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64,i386,ppc64el] http://ftp.yz.yamagata-u.ac.jp/pub/dbms/mariadb/repo/10.3/ubuntu xenial main'

- name: <MariaDB> install
  become: yes
  apt:
    name: "{{ item }}"
    force: yes
    update_cache: yes # apt updateを実行する
  with_items: "{{ mariadb_packages }}"

# - name: <MariaDB> root パスワードを設定
#   mysql_user:
#     login_user: root
#     login_password: 
#     name: root
#     password: "{{ mariadb_root_pass }}"
#   ignore_errors: yes

- name: <MariaDB> root パスワードを設定
  command: mysqladmin -u root password "{{ mariadb_root_pass }}"
  args:
    creates: "~/.alreadySettingMariaDBRootPass.lck"
  register: changed_root_pass

- name: <MariaDB> root パスワード設定済みロックファイル設置
  file:
    path: "~/.alreadySettingMariaDBRootPass.lck"
    state: touch
    mode: 0400
  when: changed_root_pass.changed

- name: <MariaDB> replace default charset
  become: yes
  replace:
    path: /etc/mysql/my.cnf
    regexp: ^character-set-server(.*)=.*(?!{{mariadb_default_charset}}).*$
    replace: "character-set-server = {{mariadb_default_charset}}"
  register: replace_default_charaset

- name: <MariaDB> set default charset
  become: yes
  blockinfile:
    path: /etc/mysql/my.cnf
    insertafter: ^\[mysqld\].*$
    block: |
      character-set-server = {{mariadb_default_charset}}
  when: replace_default_charaset.changed == false

- name: <MariaDB> コネクト制限設定 (bind-address= (127.0.0.1) >>> ({{ mariadb_bind_host }})
  become: yes
  replace:
    path: /etc/mysql/my.cnf
    regexp: ^bind-address(.*)=.*127.0.0.1.*$
    replace: "bind-address = {{ mariadb_bind_host }}"


- name: <MariaDB> evo用game database作成
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
    name: "{{ mariadb_evogame_name }}"
    state: present
    encoding: utf8

- name: <MariaDB> evo用account database作成
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
    name: "{{ mariadb_evoaccount_name }}"
    state: present
    encoding: utf8

- name: <MariaDB> evo_db_user 追加
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
    name: "{{ mariadb_user_name }}"
    password: "{{ mariadb_user_pass }}"
    host: "{{ mariadb_user_host }}"
    priv: "{{ mariadb_evogame_name }}.*:ALL/{{ mariadb_evoaccount_name }}.*:ALL"
    state: present

- name: <MariaDB> Migration用Historyテーブル作成
  shell: mysql -u{{mariadb_user_name}} -p{{mariadb_user_pass}} {{mariadb_evogame_name}} -e "CREATE TABLE IF NOT EXISTS __EFMigrationsHistory ( MigrationId nvarchar(150) NOT NULL, ProductVersion nvarchar(32) NOT NULL, PRIMARY KEY (MigrationId) );"
  changed_when: false

- name: <MariaDB> Migration用Historyテーブル作成
  shell: mysql -u{{mariadb_user_name}} -p{{mariadb_user_pass}} {{mariadb_evoaccount_name}} -e "CREATE TABLE IF NOT EXISTS __EFMigrationsHistory ( MigrationId nvarchar(150) NOT NULL, ProductVersion nvarchar(32) NOT NULL, PRIMARY KEY (MigrationId) );"
  changed_when: false


- name: <MariaDB> start & setting start on boot.
  become: yes
  service:
    name: mysql
    state: restarted
    enabled: yes
  changed_when: false
